project:
  type: website

website:
  title: "Chris Levy"
  navbar:
    left:
      - href: index.qmd
        text: About
      - blog.qmd
    right:
      - icon: github
        href: https://github.com/DrChrisLevy
      - icon: twitter
        href: https://twitter.com/cleavey1985

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

execute:
  cache: true


