ecommerce_metrics = [
    {"name": "Total Revenue", "enum": "TOTAL_REVENUE", "description": "The total amount of money earned from all sales"},
    {"name": "Average Order Value", "enum": "AVG_ORDER_VALUE", "description": "The average amount spent per order"},
    {"name": "Conversion Rate", "enum": "CONVERSION_RATE", "description": "Percentage of visitors who make a purchase"},
    {"name": "Cart Abandonment Rate", "enum": "CART_ABANDONMENT_RATE", "description": "Percentage of users who add items to cart but don't purchase"},
    {
        "name": "Customer Lifetime Value",
        "enum": "CUSTOMER_LIFETIME_VALUE",
        "description": "Predicted total revenue from a customer over their lifetime",
    },
    {"name": "Customer Acquisition Cost", "enum": "CUSTOMER_ACQUISITION_COST", "description": "Average cost to acquire a new customer"},
    {"name": "Return on Ad Spend", "enum": "RETURN_ON_AD_SPEND", "description": "Revenue generated for every dollar spent on advertising"},
    {"name": "Net Profit Margin", "enum": "NET_PROFIT_MARGIN", "description": "Percentage of revenue that becomes profit after all expenses"},
    {"name": "Repeat Purchase Rate", "enum": "REPEAT_PURCHASE_RATE", "description": "Percentage of customers who make more than one purchase"},
    {"name": "Average Time to Purchase", "enum": "AVG_TIME_TO_PURCHASE", "description": "Average time between first visit and purchase"},
    {"name": "Product Return Rate", "enum": "PRODUCT_RETURN_RATE", "description": "Percentage of sold products that are returned"},
    {
        "name": "Customer Retention Rate",
        "enum": "CUSTOMER_RETENTION_RATE",
        "description": "Percentage of customers who remain active over a given period",
    },
    {"name": "Email Click-Through Rate", "enum": "EMAIL_CTR", "description": "Percentage of email recipients who clicked on a link in the email"},
    {"name": "Site Traffic", "enum": "SITE_TRAFFIC", "description": "Total number of visitors to the e-commerce site"},
    {
        "name": "Mobile Traffic Percentage",
        "enum": "MOBILE_TRAFFIC_PERCENTAGE",
        "description": "Percentage of total traffic coming from mobile devices",
    },
    {"name": "Average Session Duration", "enum": "AVG_SESSION_DURATION", "description": "Average time users spend on the site per visit"},
    {"name": "Bounce Rate", "enum": "BOUNCE_RATE", "description": "Percentage of visitors who leave the site after viewing only one page"},
    {"name": "Pages per Session", "enum": "PAGES_PER_SESSION", "description": "Average number of pages viewed during a single session"},
    {"name": "Add to Cart Rate", "enum": "ADD_TO_CART_RATE", "description": "Percentage of sessions where a product is added to the cart"},
    {
        "name": "Checkout Completion Rate",
        "enum": "CHECKOUT_COMPLETION_RATE",
        "description": "Percentage of users who complete checkout after starting it",
    },
    {"name": "Average Order Size", "enum": "AVG_ORDER_SIZE", "description": "Average number of items per order"},
    {"name": "Revenue per Visitor", "enum": "REVENUE_PER_VISITOR", "description": "Average revenue generated per site visitor"},
    {
        "name": "Customer Satisfaction Score",
        "enum": "CUSTOMER_SATISFACTION_SCORE",
        "description": "Average rating given by customers for their shopping experience",
    },
    {"name": "Net Promoter Score", "enum": "NET_PROMOTER_SCORE", "description": "Measure of customer loyalty and likelihood to recommend"},
    {"name": "Average Response Time", "enum": "AVG_RESPONSE_TIME", "description": "Average time taken to respond to customer inquiries"},
    {
        "name": "Social Media Engagement Rate",
        "enum": "SOCIAL_MEDIA_ENGAGEMENT_RATE",
        "description": "Percentage of followers who interact with social media posts",
    },
    {
        "name": "Inventory Turnover Ratio",
        "enum": "INVENTORY_TURNOVER_RATIO",
        "description": "Number of times inventory is sold and replaced over a period",
    },
    {"name": "Out-of-Stock Rate", "enum": "OUT_OF_STOCK_RATE", "description": "Percentage of time products are unavailable due to stock issues"},
    {"name": "Average Shipping Time", "enum": "AVG_SHIPPING_TIME", "description": "Average time taken to ship an order after purchase"},
    {"name": "On-Time Delivery Rate", "enum": "ON_TIME_DELIVERY_RATE", "description": "Percentage of orders delivered within the promised timeframe"},
    {"name": "Average Discount per Order", "enum": "AVG_DISCOUNT_PER_ORDER", "description": "Average amount of discount applied per order"},
    {"name": "Coupon Redemption Rate", "enum": "COUPON_REDEMPTION_RATE", "description": "Percentage of orders using a coupon or promotional code"},
    {"name": "Gross Merchandise Value", "enum": "GROSS_MERCHANDISE_VALUE", "description": "Total value of merchandise sold through the platform"},
    {"name": "Average Margin", "enum": "AVG_MARGIN", "description": "Average profit margin across all products"},
    {"name": "Customer Support Tickets", "enum": "CUSTOMER_SUPPORT_TICKETS", "description": "Number of customer support inquiries received"},
    {
        "name": "First Contact Resolution Rate",
        "enum": "FIRST_CONTACT_RESOLUTION_RATE",
        "description": "Percentage of support issues resolved in the first interaction",
    },
    {"name": "Site Search Usage Rate", "enum": "SITE_SEARCH_USAGE_RATE", "description": "Percentage of visitors who use the site's search function"},
    {"name": "Search to Purchase Rate", "enum": "SEARCH_TO_PURCHASE_RATE", "description": "Conversion rate for visitors who use site search"},
    {
        "name": "Average Days to First Purchase",
        "enum": "AVG_DAYS_TO_FIRST_PURCHASE",
        "description": "Average number of days between account creation and first purchase",
    },
    {
        "name": "Product Page View to Purchase Rate",
        "enum": "PRODUCT_PAGE_VIEW_TO_PURCHASE_RATE",
        "description": "Percentage of product page views that result in a purchase",
    },
    {"name": "Average Revenue per User", "enum": "AVG_REVENUE_PER_USER", "description": "Average revenue generated per registered user"},
    {"name": "Customer Churn Rate", "enum": "CUSTOMER_CHURN_RATE", "description": "Percentage of customers who stop purchasing over a given period"},
    {
        "name": "Average Items per Category",
        "enum": "AVG_ITEMS_PER_CATEGORY",
        "description": "Average number of items listed in each product category",
    },
    {"name": "Category Performance", "enum": "CATEGORY_PERFORMANCE", "description": "Revenue or units sold per product category"},
    {
        "name": "New vs Returning Customer Ratio",
        "enum": "NEW_VS_RETURNING_CUSTOMER_RATIO",
        "description": "Ratio of new customers to returning customers",
    },
    {
        "name": "Average Customer Lifespan",
        "enum": "AVG_CUSTOMER_LIFESPAN",
        "description": "Average duration a customer continues to purchase from the store",
    },
    {"name": "Email Subscriber Growth Rate", "enum": "EMAIL_SUBSCRIBER_GROWTH_RATE", "description": "Rate at which email subscriber list is growing"},
    {"name": "Email Unsubscribe Rate", "enum": "EMAIL_UNSUBSCRIBE_RATE", "description": "Percentage of subscribers who unsubscribe from email list"},
    {
        "name": "Affiliate Sales Percentage",
        "enum": "AFFILIATE_SALES_PERCENTAGE",
        "description": "Percentage of sales generated through affiliate marketing",
    },
    {"name": "Mobile Conversion Rate", "enum": "MOBILE_CONVERSION_RATE", "description": "Conversion rate for visitors on mobile devices"},
    {"name": "Desktop Conversion Rate", "enum": "DESKTOP_CONVERSION_RATE", "description": "Conversion rate for visitors on desktop devices"},
    {
        "name": "Average Pages Before Purchase",
        "enum": "AVG_PAGES_BEFORE_PURCHASE",
        "description": "Average number of pages viewed before making a purchase",
    },
    {"name": "Refund Rate", "enum": "REFUND_RATE", "description": "Percentage of purchases that result in a refund"},
    {"name": "Average Refund Processing Time", "enum": "AVG_REFUND_PROCESSING_TIME", "description": "Average time taken to process a refund request"},
    {"name": "Product Review Rate", "enum": "PRODUCT_REVIEW_RATE", "description": "Percentage of purchases that result in a product review"},
    {"name": "Average Product Rating", "enum": "AVG_PRODUCT_RATING", "description": "Average star rating across all product reviews"},
    {
        "name": "Wishlist to Cart Conversion Rate",
        "enum": "WISHLIST_TO_CART_CONVERSION_RATE",
        "description": "Percentage of wishlisted items that are added to cart",
    },
    {"name": "Average Time on Product Page", "enum": "AVG_TIME_ON_PRODUCT_PAGE", "description": "Average time spent by users on product pages"},
    {"name": "Cross-Sell Success Rate", "enum": "CROSS_SELL_SUCCESS_RATE", "description": "Percentage of purchases that include a cross-sold item"},
    {"name": "Upsell Success Rate", "enum": "UPSELL_SUCCESS_RATE", "description": "Percentage of customers who accept an upsell offer"},
    {
        "name": "Average Customer Service Response Time",
        "enum": "AVG_CUSTOMER_SERVICE_RESPONSE_TIME",
        "description": "Average time taken to respond to customer service inquiries",
    },
    {
        "name": "Live Chat Engagement Rate",
        "enum": "LIVE_CHAT_ENGAGEMENT_RATE",
        "description": "Percentage of visitors who engage with live chat feature",
    },
    {
        "name": "Abandoned Cart Recovery Rate",
        "enum": "ABANDONED_CART_RECOVERY_RATE",
        "description": "Percentage of abandoned carts that are recovered through follow-up",
    },
    {"name": "Average Time to Abandon Cart", "enum": "AVG_TIME_TO_ABANDON_CART", "description": "Average time spent before a cart is abandoned"},
    {
        "name": "Product Return Reason Distribution",
        "enum": "PRODUCT_RETURN_REASON_DISTRIBUTION",
        "description": "Distribution of reasons given for product returns",
    },
    {
        "name": "Percentage of Organic Traffic",
        "enum": "PERCENTAGE_ORGANIC_TRAFFIC",
        "description": "Percentage of total traffic coming from organic search",
    },
    {"name": "Percentage of Paid Traffic", "enum": "PERCENTAGE_PAID_TRAFFIC", "description": "Percentage of total traffic coming from paid sources"},
    {"name": "Average Customer Feedback Score", "enum": "AVG_CUSTOMER_FEEDBACK_SCORE", "description": "Average score from customer feedback surveys"},
    {
        "name": "Percentage of Mobile Purchases",
        "enum": "PERCENTAGE_MOBILE_PURCHASES",
        "description": "Percentage of total purchases made on mobile devices",
    },
    {"name": "Average Session Value", "enum": "AVG_SESSION_VALUE", "description": "Average value generated per session"},
    {
        "name": "New Product Adoption Rate",
        "enum": "NEW_PRODUCT_ADOPTION_RATE",
        "description": "Rate at which new products are purchased after launch",
    },
    {
        "name": "Average Days Inventory Outstanding",
        "enum": "AVG_DAYS_INVENTORY_OUTSTANDING",
        "description": "Average number of days inventory is held before being sold",
    },
    {
        "name": "Percentage of Revenue from Top Products",
        "enum": "PERCENTAGE_REVENUE_TOP_PRODUCTS",
        "description": "Percentage of total revenue generated by top-selling products",
    },
    {
        "name": "Average Customer Query Resolution Time",
        "enum": "AVG_CUSTOMER_QUERY_RESOLUTION_TIME",
        "description": "Average time taken to fully resolve a customer query",
    },
    {
        "name": "Shopping Cart Conversion Rate",
        "enum": "SHOPPING_CART_CONVERSION_RATE",
        "description": "Percentage of carts that result in a completed purchase",
    },
    {"name": "Average Number of Login Attempts", "enum": "AVG_LOGIN_ATTEMPTS", "description": "Average number of attempts users make to log in"},
    {"name": "Password Reset Frequency", "enum": "PASSWORD_RESET_FREQUENCY", "description": "Frequency at which users reset their passwords"},
    {"name": "Average Load Time", "enum": "AVG_LOAD_TIME", "description": "Average time taken for pages to load"},
    {"name": "Mobile App Install Rate", "enum": "MOBILE_APP_INSTALL_RATE", "description": "Rate at which mobile app is installed by users"},
    {"name": "Mobile App Uninstall Rate", "enum": "MOBILE_APP_UNINSTALL_RATE", "description": "Rate at which users uninstall the mobile app"},
    {
        "name": "Average Revenue per Mobile App User",
        "enum": "AVG_REVENUE_PER_MOBILE_APP_USER",
        "description": "Average revenue generated per mobile app user",
    },
    {"name": "Push Notification Open Rate", "enum": "PUSH_NOTIFICATION_OPEN_RATE", "description": "Percentage of push notifications that are opened"},
    {
        "name": "Social Media Referral Conversion Rate",
        "enum": "SOCIAL_MEDIA_REFERRAL_CONVERSION_RATE",
        "description": "Conversion rate for traffic from social media platforms",
    },
    {"name": "Average Time to Reorder", "enum": "AVG_TIME_TO_REORDER", "description": "Average time between repeat purchases of the same product"},
    {
        "name": "Product Recommendation Click-Through Rate",
        "enum": "PRODUCT_RECOMMENDATION_CTR",
        "description": "Percentage of product recommendations that are clicked",
    },
    {"name": "Guest Checkout Rate", "enum": "GUEST_CHECKOUT_RATE", "description": "Percentage of purchases made by guest users"},
    {"name": "Account Creation Rate", "enum": "ACCOUNT_CREATION_RATE", "description": "Rate at which new user accounts are created"},
    {
        "name": "Average Products Viewed per Session",
        "enum": "AVG_PRODUCTS_VIEWED_PER_SESSION",
        "description": "Average number of product pages viewed in a single session",
    },
    {"name": "Product Image Zoom Rate", "enum": "PRODUCT_IMAGE_ZOOM_RATE", "description": "Percentage of product page views where images are zoomed"},
    {
        "name": "Product Video View Rate",
        "enum": "PRODUCT_VIDEO_VIEW_RATE",
        "description": "Percentage of product page views where videos are watched",
    },
    {"name": "Average Video Watch Time", "enum": "AVG_VIDEO_WATCH_TIME", "description": "Average duration of product video views"},
    {"name": "Frequency of Price Changes", "enum": "FREQUENCY_PRICE_CHANGES", "description": "How often product prices are updated"},
    {"name": "Price Elasticity of Demand", "enum": "PRICE_ELASTICITY_DEMAND", "description": "Measure of how demand changes with price changes"},
    {"name": "Average Time to Checkout", "enum": "AVG_TIME_TO_CHECKOUT", "description": "Average time taken to complete the checkout process"},
    {"name": "Form Field Error Rate", "enum": "FORM_FIELD_ERROR_RATE", "description": "Percentage of form submissions with errors"},
    {
        "name": "Payment Gateway Error Rate",
        "enum": "PAYMENT_GATEWAY_ERROR_RATE",
        "description": "Percentage of transactions with payment gateway errors",
    },
    {
        "name": "Average Customer Support Tickets per Order",
        "enum": "AVG_SUPPORT_TICKETS_PER_ORDER",
        "description": "Average number of support tickets generated per order",
    },
    {"name": "Product Question Frequency", "enum": "PRODUCT_QUESTION_FREQUENCY", "description": "Average number of questions asked per product"},
    {"name": "Question Response Time", "enum": "QUESTION_RESPONSE_TIME", "description": "Average time taken to respond to product questions"},
    {
        "name": "User-Generated Content Submission Rate",
        "enum": "UGC_SUBMISSION_RATE",
        "description": "Rate at which users submit reviews, photos, or videos",
    },
    {"name": "Influencer Campaign ROI", "enum": "INFLUENCER_CAMPAIGN_ROI", "description": "Return on investment for influencer marketing campaigns"},
    {
        "name": "Average Order Processing Time",
        "enum": "AVG_ORDER_PROCESSING_TIME",
        "description": "Average time taken to process an order before shipping",
    },
    {
        "name": "Shipping Cost as Percentage of Order Value",
        "enum": "SHIPPING_COST_PERCENTAGE",
        "description": "Average shipping cost as a percentage of total order value",
    },
    {
        "name": "Free Shipping Threshold Effectiveness",
        "enum": "FREE_SHIPPING_THRESHOLD_EFFECTIVENESS",
        "description": "Percentage of orders that qualify for free shipping",
    },
    {
        "name": "Average Additional Spend for Free Shipping",
        "enum": "AVG_ADDITIONAL_SPEND_FREE_SHIPPING",
        "description": "Average amount spent to reach free shipping threshold",
    },
    {"name": "Seasonal Sales Variation", "enum": "SEASONAL_SALES_VARIATION", "description": "Measure of how sales fluctuate across seasons"},
    {
        "name": "Holiday Season Sales Percentage",
        "enum": "HOLIDAY_SEASON_SALES_PERCENTAGE",
        "description": "Percentage of annual sales occurring during holiday season",
    },
    {"name": "Average Time Between Sales", "enum": "AVG_TIME_BETWEEN_SALES", "description": "Average time gap between individual sales"},
    {
        "name": "Product Bundling Effectiveness",
        "enum": "PRODUCT_BUNDLING_EFFECTIVENESS",
        "description": "Measure of how well product bundles perform compared to individual products",
    },
    {"name": "Gift Card Purchase Rate", "enum": "GIFT_CARD_PURCHASE_RATE", "description": "Percentage of orders that include gift card purchases"},
    {"name": "Gift Card Redemption Rate", "enum": "GIFT_CARD_REDEMPTION_RATE", "description": "Percentage of sold gift cards that are redeemed"},
    {"name": "Average Gift Card Value", "enum": "AVG_GIFT_CARD_VALUE", "description": "Average monetary value of gift cards purchased"},
    {
        "name": "Loyalty Program Enrollment Rate",
        "enum": "LOYALTY_PROGRAM_ENROLLMENT_RATE",
        "description": "Percentage of customers enrolled in loyalty program",
    },
    {"name": "Loyalty Point Redemption Rate", "enum": "LOYALTY_POINT_REDEMPTION_RATE", "description": "Rate at which loyalty points are redeemed"},
    {"name": "Average Loyalty Program ROI", "enum": "AVG_LOYALTY_PROGRAM_ROI", "description": "Return on investment for the loyalty program"},
    {
        "name": "Product Comparison Usage Rate",
        "enum": "PRODUCT_COMPARISON_USAGE_RATE",
        "description": "Percentage of sessions where product comparison tool is used",
    },
    {"name": "Wishlist Addition Rate", "enum": "WISHLIST_ADDITION_RATE", "description": "Rate at which products are added to wishlists"},
    {"name": "Wishlist Removal Rate", "enum": "WISHLIST_REMOVAL_RATE", "description": "Rate at which products are removed from wishlists"},
    {"name": "Average Wishlist Size", "enum": "AVG_WISHLIST_SIZE", "description": "Average number of items in user wishlists"},
    {
        "name": "Product Stock Alert Subscription Rate",
        "enum": "PRODUCT_STOCK_ALERT_SUBSCRIPTION_RATE",
        "description": "Rate at which users subscribe to out-of-stock product alerts",
    },
    {
        "name": "Stock Alert Conversion Rate",
        "enum": "STOCK_ALERT_CONVERSION_RATE",
        "description": "Percentage of stock alert subscribers who purchase when item is back in stock",
    },
    {"name": "Average Time to Restock", "enum": "AVG_TIME_TO_RESTOCK", "description": "Average time taken to restock out-of-stock items"},
    {
        "name": "Percentage of Sales from Marketplace vs. Direct",
        "enum": "PERCENTAGE_SALES_MARKETPLACE_VS_DIRECT",
        "description": "Distribution of sales between marketplace and direct channels",
    },
    {"name": "Average Seller Rating", "enum": "AVG_SELLER_RATING", "description": "Average rating given to sellers (for marketplace models)"},
    {"name": "Seller Onboarding Time", "enum": "SELLER_ONBOARDING_TIME", "description": "Average time taken to onboard new sellers"},
    {"name": "Seller Churn Rate", "enum": "SELLER_CHURN_RATE", "description": "Rate at which sellers leave the platform"},
    {"name": "Average Commission Rate", "enum": "AVG_COMMISSION_RATE", "description": "Average commission charged to sellers"},
    {
        "name": "International Sales Percentage",
        "enum": "INTERNATIONAL_SALES_PERCENTAGE",
        "description": "Percentage of sales from international customers",
    },
    {"name": "Currency Conversion Rate", "enum": "CURRENCY_CONVERSION_RATE", "description": "Rate at which users switch to a different currency"},
    {"name": "Language Switch Rate", "enum": "LANGUAGE_SWITCH_RATE", "description": "Rate at which users switch the site language"},
    {
        "name": "Average Translation Quality Score",
        "enum": "AVG_TRANSLATION_QUALITY_SCORE",
        "description": "Average quality score for translated content",
    },
    {"name": "Accessibility Score", "enum": "ACCESSIBILITY_SCORE", "description": "Measure of the site's accessibility for users with disabilities"},
    {"name": "Voice Search Usage Rate", "enum": "VOICE_SEARCH_USAGE_RATE", "description": "Percentage of searches conducted using voice commands"},
    {"name": "Image Search Usage Rate", "enum": "IMAGE_SEARCH_USAGE_RATE", "description": "Percentage of searches conducted using image uploads"},
    {"name": "AR Feature Usage Rate", "enum": "AR_FEATURE_USAGE_RATE", "description": "Rate at which augmented reality features are used"},
    {
        "name": "Virtual Try-On Conversion Rate",
        "enum": "VIRTUAL_TRY_ON_CONVERSION_RATE",
        "description": "Conversion rate for products with virtual try-on feature",
    },
    {"name": "AI Chatbot Usage Rate", "enum": "AI_CHATBOT_USAGE_RATE", "description": "Percentage of customer interactions handled by AI chatbots"},
    {
        "name": "AI Chatbot Resolution Rate",
        "enum": "AI_CHATBOT_RESOLUTION_RATE",
        "description": "Percentage of queries successfully resolved by AI chatbots",
    },
    {
        "name": "Progressive Web App Adoption Rate",
        "enum": "PWA_ADOPTION_RATE",
        "description": "Rate at which users adopt the progressive web app version",
    },
    {"name": "Average Page Load Speed", "enum": "AVG_PAGE_LOAD_SPEED", "description": "Average time taken for pages to fully load"},
    {"name": "Server Response Time", "enum": "SERVER_RESPONSE_TIME", "description": "Average time taken for server to respond to requests"},
    {"name": "API Response Time", "enum": "API_RESPONSE_TIME", "description": "Average response time for API calls"},
    {"name": "CDN Cache Hit Rate", "enum": "CDN_CACHE_HIT_RATE", "description": "Percentage of content served from CDN cache"},
    {"name": "Database Query Performance", "enum": "DATABASE_QUERY_PERFORMANCE", "description": "Average execution time of database queries"},
    {
        "name": "Peak Hour Performance Degradation",
        "enum": "PEAK_HOUR_PERFORMANCE_DEGRADATION",
        "description": "Measure of performance decline during peak traffic hours",
    },
    {"name": "Mobile App Crash Rate", "enum": "MOBILE_APP_CRASH_RATE", "description": "Frequency of mobile app crashes"},
    {
        "name": "Browser Compatibility Score",
        "enum": "BROWSER_COMPATIBILITY_SCORE",
        "description": "Measure of site's compatibility across different browsers",
    },
    {
        "name": "Average API Calls per Session",
        "enum": "AVG_API_CALLS_PER_SESSION",
        "description": "Average number of API calls made during a user session",
    },
    {"name": "Third-Party Script Load Time", "enum": "THIRD_PARTY_SCRIPT_LOAD_TIME", "description": "Average load time for third-party scripts"},
]

brands = [
    {"name": "TechNova", "enum": "TECH_NOVA", "description": "Innovative consumer electronics manufacturer"},
    {"name": "EcoGreen", "enum": "ECO_GREEN", "description": "Sustainable home goods and appliances"},
    {"name": "FitFlex", "enum": "FIT_FLEX", "description": "Athletic wear and fitness equipment"},
    {"name": "Luxe Living", "enum": "LUXE_LIVING", "description": "High-end furniture and home decor"},
    {"name": "GourmetDelight", "enum": "GOURMET_DELIGHT", "description": "Premium food and kitchen products"},
    {"name": "Nike", "enum": "NIKE", "description": "Global sportswear and athletic footwear brand"},
    {"name": "Apple", "enum": "APPLE", "description": "Multinational technology company"},
    {"name": "Amazon", "enum": "AMAZON", "description": "E-commerce and cloud computing giant"},
    {"name": "PetPal", "enum": "PET_PAL", "description": "Pet supplies and accessories"},
    {"name": "BeautyBliss", "enum": "BEAUTY_BLISS", "description": "Cosmetics and skincare products"},
    {"name": "Toyota", "enum": "TOYOTA", "description": "Japanese automotive manufacturer"},
    {"name": "Zara", "enum": "ZARA", "description": "Fast fashion clothing retailer"},
    {"name": "BookWorm", "enum": "BOOK_WORM", "description": "Online bookstore and e-reader devices"},
    {"name": "GreenThumb", "enum": "GREEN_THUMB", "description": "Gardening supplies and outdoor furniture"},
    {"name": "ToyWorld", "enum": "TOY_WORLD", "description": "Children's toys and educational products"},
    {"name": "Samsung", "enum": "SAMSUNG", "description": "South Korean electronics conglomerate"},
    {"name": "Adidas", "enum": "ADIDAS", "description": "German sportswear manufacturer"},
    {"name": "IKEA", "enum": "IKEA", "description": "Swedish-founded furniture retailer"},
    {"name": "MusicMaster", "enum": "MUSIC_MASTER", "description": "Musical instruments and accessories"},
    {"name": "CraftCorner", "enum": "CRAFT_CORNER", "description": "Art supplies and craft materials"},
    {"name": "Microsoft", "enum": "MICROSOFT", "description": "Multinational technology corporation"},
    {"name": "Coca-Cola", "enum": "COCA_COLA", "description": "Global beverage company"},
    {"name": "AutoPro", "enum": "AUTO_PRO", "description": "Automotive parts and accessories"},
    {"name": "HomeSmart", "enum": "HOME_SMART", "description": "Smart home devices and systems"},
    {"name": "FreshFarms", "enum": "FRESH_FARMS", "description": "Organic produce and grocery items"},
    {"name": "Google", "enum": "GOOGLE", "description": "Internet-related services and products"},
    {"name": "Nestle", "enum": "NESTLE", "description": "Multinational food and drink company"},
    {"name": "TravelEase", "enum": "TRAVEL_EASE", "description": "Luggage and travel accessories"},
    {"name": "FitBit", "enum": "FITBIT", "description": "Fitness trackers and smartwatches"},
    {"name": "CozyHome", "enum": "COZY_HOME", "description": "Bedding and home textiles"},
    {"name": "Disney", "enum": "DISNEY", "description": "Entertainment and media conglomerate"},
    {"name": "Sony", "enum": "SONY", "description": "Japanese multinational conglomerate"},
    {"name": "OfficeMax", "enum": "OFFICE_MAX", "description": "Office supplies and furniture"},
    {"name": "SportsPro", "enum": "SPORTS_PRO", "description": "Professional sports equipment"},
    {"name": "BabyBliss", "enum": "BABY_BLISS", "description": "Baby products and accessories"},
    {"name": "McDonald's", "enum": "MCDONALDS", "description": "Global fast food restaurant chain"},
    {"name": "Walmart", "enum": "WALMART", "description": "Multinational retail corporation"},
    {"name": "GamerZone", "enum": "GAMER_ZONE", "description": "Video games and gaming accessories"},
    {"name": "CampGear", "enum": "CAMP_GEAR", "description": "Camping and outdoor equipment"},
    {"name": "JewelGlow", "enum": "JEWEL_GLOW", "description": "Jewelry and accessories"},
    {"name": "Starbucks", "enum": "STARBUCKS", "description": "Multinational chain of coffeehouses"},
    {"name": "Dell", "enum": "DELL", "description": "Computer technology company"},
    {"name": "PetSmart", "enum": "PETSMART", "description": "Pet supplies retailer"},
    {"name": "FitnessFuel", "enum": "FITNESS_FUEL", "description": "Nutritional supplements and protein powders"},
    {"name": "ArtisanCrafts", "enum": "ARTISAN_CRAFTS", "description": "Handmade and artisanal products"},
    {"name": "Unilever", "enum": "UNILEVER", "description": "Consumer goods company"},
    {"name": "BMW", "enum": "BMW", "description": "Luxury vehicle manufacturer"},
    {"name": "PartyPop", "enum": "PARTY_POP", "description": "Party supplies and decorations"},
    {"name": "TechGeek", "enum": "TECH_GEEK", "description": "Gadgets and tech accessories"},
    {"name": "GreenEnergy", "enum": "GREEN_ENERGY", "description": "Renewable energy products"},
    {"name": "Lego", "enum": "LEGO", "description": "Plastic construction toys"},
    {"name": "Gap", "enum": "GAP", "description": "American clothing and accessories retailer"},
    {"name": "HealthyHeart", "enum": "HEALTHY_HEART", "description": "Health monitoring devices"},
    {"name": "CoffeeWorld", "enum": "COFFEE_WORLD", "description": "Coffee makers and accessories"},
    {"name": "DiyDepot", "enum": "DIY_DEPOT", "description": "Home improvement and DIY supplies"},
    {"name": "Procter & Gamble", "enum": "PROCTER_AND_GAMBLE", "description": "Consumer goods corporation"},
    {"name": "H&M", "enum": "H_AND_M", "description": "Swedish multinational clothing company"},
    {"name": "VintageFinds", "enum": "VINTAGE_FINDS", "description": "Antique and vintage items"},
    {"name": "FitKitchen", "enum": "FIT_KITCHEN", "description": "Healthy cooking appliances"},
    {"name": "EcoTravel", "enum": "ECO_TRAVEL", "description": "Eco-friendly travel gear"},
    {"name": "Netflix", "enum": "NETFLIX", "description": "Streaming entertainment service"},
    {"name": "Canon", "enum": "CANON", "description": "Imaging and optical products manufacturer"},
    {"name": "GourmetGrills", "enum": "GOURMET_GRILLS", "description": "High-end grilling equipment"},
    {"name": "SmartStudy", "enum": "SMART_STUDY", "description": "Educational technology products"},
    {"name": "PetLuxe", "enum": "PET_LUXE", "description": "Luxury pet products"},
    {"name": "Visa", "enum": "VISA", "description": "Global payments technology company"},
    {"name": "Philips", "enum": "PHILIPS", "description": "Dutch technology company"},
    {"name": "Urban Outfitters", "enum": "URBAN_OUTFITTERS", "description": "Lifestyle retail company"},
    {"name": "FreshBeauty", "enum": "FRESH_BEAUTY", "description": "Natural and organic beauty products"},
    {"name": "HomeChef", "enum": "HOME_CHEF", "description": "Gourmet meal kits and ingredients"},
    {"name": "PayPal", "enum": "PAYPAL", "description": "Online payments system"},
    {"name": "LG", "enum": "LG", "description": "South Korean electronics company"},
    {"name": "SleepWell", "enum": "SLEEP_WELL", "description": "Sleep aids and bedding products"},
    {"name": "FitFashion", "enum": "FIT_FASHION", "description": "Athleisure and activewear"},
    {"name": "CleanGreen", "enum": "CLEAN_GREEN", "description": "Eco-friendly cleaning products"},
    {"name": "Spotify", "enum": "SPOTIFY", "description": "Digital music streaming service"},
    {"name": "Panasonic", "enum": "PANASONIC", "description": "Japanese electronics corporation"},
    {"name": "BookNook", "enum": "BOOK_NOOK", "description": "Bookstore and reading accessories"},
    {"name": "PetFit", "enum": "PET_FIT", "description": "Pet fitness and health products"},
    {"name": "BeautyBoutique", "enum": "BEAUTY_BOUTIQUE", "description": "High-end beauty and skincare"},
    {"name": "MasterCard", "enum": "MASTERCARD", "description": "Multinational financial services corporation"},
    {"name": "Lenovo", "enum": "LENOVO", "description": "Chinese multinational technology company"},
    {"name": "OutdoorAdventure", "enum": "OUTDOOR_ADVENTURE", "description": "Outdoor and adventure gear"},
    {"name": "SmartHome", "enum": "SMART_HOME", "description": "Home automation products"},
    {"name": "GourmetSnacks", "enum": "GOURMET_SNACKS", "description": "Premium snack foods"},
    {"name": "Adobe", "enum": "ADOBE", "description": "Software company"},
    {"name": "Huawei", "enum": "HUAWEI", "description": "Chinese telecommunications company"},
    {"name": "FreshFace", "enum": "FRESH_FACE", "description": "Skincare and facial products"},
    {"name": "PetPamper", "enum": "PET_PAMPER", "description": "Pet grooming and care products"},
    {"name": "EcoFashion", "enum": "ECO_FASHION", "description": "Sustainable clothing and accessories"},
    {"name": "Twitter", "enum": "TWITTER", "description": "Social networking service"},
    {"name": "Bosch", "enum": "BOSCH", "description": "German multinational engineering company"},
    {"name": "KidSmart", "enum": "KID_SMART", "description": "Educational toys and games"},
    {"name": "FitBites", "enum": "FIT_BITES", "description": "Healthy snacks and meal replacements"},
    {"name": "HomeHarmony", "enum": "HOME_HARMONY", "description": "Home organization and storage solutions"},
    {"name": "LinkedIn", "enum": "LINKEDIN", "description": "Business and employment-oriented social networking service"},
    {"name": "Nikon", "enum": "NIKON", "description": "Japanese multinational optics and imaging products corporation"},
    {"name": "GreenGarden", "enum": "GREEN_GARDEN", "description": "Organic gardening supplies"},
    {"name": "TechTrend", "enum": "TECH_TREND", "description": "Cutting-edge technology accessories"},
    {"name": "FitFuel", "enum": "FIT_FUEL", "description": "Sports nutrition and energy products"},
    {"name": "Pinterest", "enum": "PINTEREST", "description": "Image sharing and social media service"},
    {"name": "Dyson", "enum": "DYSON", "description": "Technology company specializing in household appliances"},
    {"name": "EcoClean", "enum": "ECO_CLEAN", "description": "Environmentally friendly cleaning products"},
    {"name": "PetGourmet", "enum": "PET_GOURMET", "description": "Gourmet pet food and treats"},
    {"name": "BeautyTech", "enum": "BEAUTY_TECH", "description": "High-tech beauty devices"},
    {"name": "Airbnb", "enum": "AIRBNB", "description": "Online marketplace for lodging and tourism experiences"},
    {"name": "GoPro", "enum": "GOPRO", "description": "Action camera and mobile app company"},
    {"name": "GreenMobility", "enum": "GREEN_MOBILITY", "description": "Eco-friendly transportation solutions"},
    {"name": "FitTech", "enum": "FIT_TECH", "description": "Fitness technology and wearables"},
    {"name": "HomeArtisan", "enum": "HOME_ARTISAN", "description": "Handcrafted home decor"},
    {"name": "Uber", "enum": "UBER", "description": "Transportation network company"},
    {"name": "Bose", "enum": "BOSE", "description": "Audio equipment company"},
    {"name": "NaturalNurture", "enum": "NATURAL_NURTURE", "description": "Organic baby products"},
    {"name": "TechPlay", "enum": "TECH_PLAY", "description": "Educational technology toys"},
    {"name": "EcoWear", "enum": "ECO_WEAR", "description": "Sustainable clothing brand"},
    {"name": "Etsy", "enum": "ETSY", "description": "E-commerce website focused on handmade or vintage items"},
    {"name": "Garmin", "enum": "GARMIN", "description": "GPS technology company"},
    {"name": "CulinaryCreations", "enum": "CULINARY_CREATIONS", "description": "Gourmet cooking tools and appliances"},
    {"name": "PetTech", "enum": "PET_TECH", "description": "Pet technology and smart devices"},
    {"name": "BeautyEssentials", "enum": "BEAUTY_ESSENTIALS", "description": "Essential beauty and skincare products"},
    {"name": "Slack", "enum": "SLACK", "description": "Business communication platform"},
    {"name": "Roomba", "enum": "ROOMBA", "description": "Robotic vacuum cleaner brand"},
    {"name": "EcoPackage", "enum": "ECO_PACKAGE", "description": "Sustainable packaging solutions"},
    {"name": "FitMind", "enum": "FIT_MIND", "description": "Mental fitness and wellness products"},
    {"name": "SmartKitchen", "enum": "SMART_KITCHEN", "description": "Connected kitchen appliances"},
    {"name": "Zoom", "enum": "ZOOM", "description": "Video communications company"},
    {"name": "GreenPackaging", "enum": "GREEN_PACKAGING", "description": "Eco-friendly packaging materials"},
    {"name": "TechLearn", "enum": "TECH_LEARN", "description": "Online learning platforms and tools"},
    {"name": "PetComfort", "enum": "PET_COMFORT", "description": "Comfort-focused pet products"},
    {"name": "Shopify", "enum": "SHOPIFY", "description": "E-commerce platform for online stores"},
    {"name": "Ring", "enum": "RING", "description": "Smart home security products"},
    {"name": "EcoTravel", "enum": "ECO_TRAVEL", "description": "Sustainable travel gear and accessories"},
    {"name": "FitSleep", "enum": "FIT_SLEEP", "description": "Sleep tracking and improvement products"},
    {"name": "ArtisanEats", "enum": "ARTISAN_EATS", "description": "Artisanal and specialty foods"},
]

sales_channels = [
    {"name": "Amazon", "enum": "AMAZON", "description": "World's largest e-commerce marketplace"},
    {"name": "eBay", "enum": "EBAY", "description": "Global online marketplace for new and used goods"},
    {"name": "Walmart Marketplace", "enum": "WALMART_MARKETPLACE", "description": "Online marketplace by Walmart"},
    {"name": "Etsy", "enum": "ETSY", "description": "E-commerce website focused on handmade or vintage items"},
    {"name": "Own Website", "enum": "OWN_WEBSITE", "description": "Company's proprietary e-commerce website"},
    {"name": "Physical Stores", "enum": "PHYSICAL_STORES", "description": "Brick-and-mortar retail locations"},
    {"name": "Instagram Shopping", "enum": "INSTAGRAM_SHOPPING", "description": "In-app shopping feature on Instagram"},
    {"name": "Facebook Marketplace", "enum": "FACEBOOK_MARKETPLACE", "description": "Peer-to-peer and business-to-consumer marketplace on Facebook"},
    {"name": "Google Shopping", "enum": "GOOGLE_SHOPPING", "description": "Google's shopping search engine"},
    {"name": "Shopify", "enum": "SHOPIFY", "description": "E-commerce platform for online stores and retail point-of-sale systems"},
    {"name": "Target Plus", "enum": "TARGET_PLUS", "description": "Target's third-party seller program"},
    {"name": "Newegg", "enum": "NEWEGG", "description": "Online retailer of computer hardware and consumer electronics"},
    {"name": "Overstock", "enum": "OVERSTOCK", "description": "Online retailer selling a broad range of products"},
    {"name": "Wayfair", "enum": "WAYFAIR", "description": "E-commerce company that sells furniture and home-goods"},
    {"name": "Wish", "enum": "WISH", "description": "Mobile e-commerce platform"},
]

questions = [
    {
        "question": "What was the Total Revenue for Nike and Adidas on Amazon and eBay from January 1, 2024 to March 31, 2024?",
        "expected_metric": "TOTAL_REVENUE",
        "expected_brands": ["NIKE", "ADIDAS"],
        "expected_sales_channels": ["AMAZON", "EBAY"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-03-31",
    },
    {
        "question": "Calculate the Average Order Value for Apple products sold through their Own Website between April 1, 2024 and May 31, 2024.",
        "expected_metric": "AVG_ORDER_VALUE",
        "expected_brands": ["APPLE"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "What was the Conversion Rate for Samsung on Walmart Marketplace during the first quarter of 2024?",
        "expected_metric": "CONVERSION_RATE",
        "expected_brands": ["SAMSUNG"],
        "expected_sales_channels": ["WALMART_MARKETPLACE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-03-31",
    },
    {
        "question": "Determine the Cart Abandonment Rate for IKEA on their Own Website and Physical Stores from May 1, 2024 to June 9, 2024.",
        "expected_metric": "CART_ABANDONMENT_RATE",
        "expected_brands": ["IKEA"],
        "expected_sales_channels": ["OWN_WEBSITE", "PHYSICAL_STORES"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Customer Lifetime Value for FitFlex customers who purchased through Instagram Shopping in the last 30 days?",
        "expected_metric": "CUSTOMER_LIFETIME_VALUE",
        "expected_brands": ["FIT_FLEX"],
        "expected_sales_channels": ["INSTAGRAM_SHOPPING"],
        "current_period_start_date": "2024-05-11",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Calculate the Customer Acquisition Cost for EcoGreen on Etsy and Amazon for the month of April 2024.",
        "expected_metric": "CUSTOMER_ACQUISITION_COST",
        "expected_brands": ["ECO_GREEN"],
        "expected_sales_channels": ["ETSY", "AMAZON"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-04-30",
    },
    {
        "question": "What was the Return on Ad Spend for Luxe Living on Google Shopping from February 15, 2024 to May 15, 2024?",
        "expected_metric": "RETURN_ON_AD_SPEND",
        "expected_brands": ["LUXE_LIVING"],
        "expected_sales_channels": ["GOOGLE_SHOPPING"],
        "current_period_start_date": "2024-02-15",
        "current_period_end_date": "2024-05-15",
    },
    {
        "question": "Determine the Net Profit Margin for GourmetDelight on their Own Website for the second quarter of 2024.",
        "expected_metric": "NET_PROFIT_MARGIN",
        "expected_brands": ["GOURMET_DELIGHT"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Repeat Purchase Rate for PetPal on Amazon from March 1, 2024 to May 31, 2024?",
        "expected_metric": "REPEAT_PURCHASE_RATE",
        "expected_brands": ["PET_PAL"],
        "expected_sales_channels": ["AMAZON"],
        "current_period_start_date": "2024-03-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "Calculate the Average Time to Purchase for BeautyBliss products on Sephora's website in May 2024.",
        "expected_metric": "AVG_TIME_TO_PURCHASE",
        "expected_brands": ["BEAUTY_BLISS"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "What was the Product Return Rate for Zara on their Own Website and Physical Stores from April 1, 2024 to June 9, 2024?",
        "expected_metric": "PRODUCT_RETURN_RATE",
        "expected_brands": ["ZARA"],
        "expected_sales_channels": ["OWN_WEBSITE", "PHYSICAL_STORES"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Determine the Customer Retention Rate for BookWorm on Amazon and their Own Website for the first half of 2024.",
        "expected_metric": "CUSTOMER_RETENTION_RATE",
        "expected_brands": ["BOOK_WORM"],
        "expected_sales_channels": ["AMAZON", "OWN_WEBSITE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Email Click-Through Rate for GreenThumb's marketing campaigns on their Own Website from May 1, 2024 to June 9, 2024?",
        "expected_metric": "EMAIL_CTR",
        "expected_brands": ["GREEN_THUMB"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Calculate the Site Traffic for ToyWorld on their Own Website and Walmart Marketplace for the second quarter of 2024.",
        "expected_metric": "SITE_TRAFFIC",
        "expected_brands": ["TOY_WORLD"],
        "expected_sales_channels": ["OWN_WEBSITE", "WALMART_MARKETPLACE"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Mobile Traffic Percentage for Adidas on their Own Website and Instagram Shopping in May 2024?",
        "expected_metric": "MOBILE_TRAFFIC_PERCENTAGE",
        "expected_brands": ["ADIDAS"],
        "expected_sales_channels": ["OWN_WEBSITE", "INSTAGRAM_SHOPPING"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "Determine the Average Session Duration for MusicMaster on their Own Website from April 15, 2024 to May 15, 2024.",
        "expected_metric": "AVG_SESSION_DURATION",
        "expected_brands": ["MUSIC_MASTER"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-04-15",
        "current_period_end_date": "2024-05-15",
    },
    {
        "question": "What was the Bounce Rate for CraftCorner on Etsy and their Own Website for the first five months of 2024?",
        "expected_metric": "BOUNCE_RATE",
        "expected_brands": ["CRAFT_CORNER"],
        "expected_sales_channels": ["ETSY", "OWN_WEBSITE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "Calculate the Pages per Session for Microsoft's through their own website from March 1, 2024 to May 31, 2024.",
        "expected_metric": "PAGES_PER_SESSION",
        "expected_brands": ["MICROSOFT"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-03-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "What was the Add to Cart Rate for AutoPro on Amazon and eBay during April 2024?",
        "expected_metric": "ADD_TO_CART_RATE",
        "expected_brands": ["AUTO_PRO"],
        "expected_sales_channels": ["AMAZON", "EBAY"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-04-30",
    },
    {
        "question": "Determine the Checkout Completion Rate for HomeSmart on their Own Website and Google Shopping from May 1, 2024 to June 9, 2024.",
        "expected_metric": "CHECKOUT_COMPLETION_RATE",
        "expected_brands": ["HOME_SMART"],
        "expected_sales_channels": ["OWN_WEBSITE", "GOOGLE_SHOPPING"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Average Order Size for FreshFarms on Walmart Marketplace and their Own Website in the last 60 days?",
        "expected_metric": "AVG_ORDER_SIZE",
        "expected_brands": ["FRESH_FARMS"],
        "expected_sales_channels": ["WALMART_MARKETPLACE", "OWN_WEBSITE"],
        "current_period_start_date": "2024-04-11",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Calculate the Revenue per Visitor for Nestle on Amazon and Walmart Marketplace for the second quarter of 2024.",
        "expected_metric": "REVENUE_PER_VISITOR",
        "expected_brands": ["NESTLE"],
        "expected_sales_channels": ["AMAZON", "WALMART_MARKETPLACE"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Customer Satisfaction Score for TravelEase on their Own Website from January 1, 2024 to May 31, 2024?",
        "expected_metric": "CUSTOMER_SATISFACTION_SCORE",
        "expected_brands": ["TRAVEL_EASE"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "Determine the Net Promoter Score for FitBit on Amazon and their Own Website for the month of May 2024.",
        "expected_metric": "NET_PROMOTER_SCORE",
        "expected_brands": ["FITBIT"],
        "expected_sales_channels": ["AMAZON", "OWN_WEBSITE"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "What was the Average Response Time for CozyHome's customer service on their Own Website from April 1, 2024 to June 9, 2024?",
        "expected_metric": "AVG_RESPONSE_TIME",
        "expected_brands": ["COZY_HOME"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Calculate the Social Media Engagement Rate for Disney on Instagram Shopping and Facebook Marketplace for the second quarter of 2024.",
        "expected_metric": "SOCIAL_MEDIA_ENGAGEMENT_RATE",
        "expected_brands": ["DISNEY"],
        "expected_sales_channels": ["INSTAGRAM_SHOPPING", "FACEBOOK_MARKETPLACE"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Inventory Turnover Ratio for Sony on Amazon and their Own Website from March 1, 2024 to May 31, 2024?",
        "expected_metric": "INVENTORY_TURNOVER_RATIO",
        "expected_brands": ["SONY"],
        "expected_sales_channels": ["AMAZON", "OWN_WEBSITE"],
        "current_period_start_date": "2024-03-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "Determine the Out-of-Stock Rate for OfficeMax on Staples.com and their Own Website for the month of May 2024.",
        "expected_metric": "OUT_OF_STOCK_RATE",
        "expected_brands": ["OFFICE_MAX"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "What was the Average Shipping Time for SportsPro orders on Amazon and eBay from April 15, 2024 to May 15, 2024?",
        "expected_metric": "AVG_SHIPPING_TIME",
        "expected_brands": ["SPORTS_PRO"],
        "expected_sales_channels": ["AMAZON", "EBAY"],
        "current_period_start_date": "2024-04-15",
        "current_period_end_date": "2024-05-15",
    },
    {
        "question": "Calculate the On-Time Delivery Rate for BabyBliss on their Own Website and Walmart Marketplace for the second quarter of 2024.",
        "expected_metric": "ON_TIME_DELIVERY_RATE",
        "expected_brands": ["BABY_BLISS"],
        "expected_sales_channels": ["OWN_WEBSITE", "WALMART_MARKETPLACE"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Average Discount per Order for Walmart on their Own Website and Physical Stores from May 1, 2024 to June 9, 2024?",
        "expected_metric": "AVG_DISCOUNT_PER_ORDER",
        "expected_brands": ["WALMART"],
        "expected_sales_channels": ["OWN_WEBSITE", "PHYSICAL_STORES"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Determine the Coupon Redemption Rate for GamerZone on their Own Website and Amazon for the month of April 2024.",
        "expected_metric": "COUPON_REDEMPTION_RATE",
        "expected_brands": ["GAMER_ZONE"],
        "expected_sales_channels": ["OWN_WEBSITE", "AMAZON"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-04-30",
    },
    {
        "question": "What was the Gross Merchandise Value for CampGear on REI.com and their Own Website from January 1, 2024 to May 31, 2024?",
        "expected_metric": "GROSS_MERCHANDISE_VALUE",
        "expected_brands": ["CAMP_GEAR"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "What was the Total Revenue for Apple on Amazon and their Own Website from January 1, 2024 to March 31, 2024?",
        "expected_metric": "TOTAL_REVENUE",
        "expected_brands": ["APPLE"],
        "expected_sales_channels": ["AMAZON", "OWN_WEBSITE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-03-31",
    },
    {
        "question": "Calculate the Average Order Value for Nike products on Instagram Shopping and Facebook Marketplace between April 15, 2024 and June 1, 2024.",
        "expected_metric": "AVG_ORDER_VALUE",
        "expected_brands": ["NIKE"],
        "expected_sales_channels": ["INSTAGRAM_SHOPPING", "FACEBOOK_MARKETPLACE"],
        "current_period_start_date": "2024-04-15",
        "current_period_end_date": "2024-06-01",
    },
    {
        "question": "What was the Conversion Rate for Samsung on their Own Website from May 1, 2024 to June 9, 2024?",
        "expected_metric": "CONVERSION_RATE",
        "expected_brands": ["SAMSUNG"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Determine the Customer Lifetime Value for FitFlex and EcoGreen on Amazon and eBay from February 1, 2024 to April 30, 2024.",
        "expected_metric": "CUSTOMER_LIFETIME_VALUE",
        "expected_brands": ["FIT_FLEX", "ECO_GREEN"],
        "expected_sales_channels": ["AMAZON", "EBAY"],
        "current_period_start_date": "2024-02-01",
        "current_period_end_date": "2024-04-30",
    },
    {
        "question": "What was the Customer Acquisition Cost for Luxe Living on Wayfair and Overstock from March 15, 2024 to May 31, 2024?",
        "expected_metric": "CUSTOMER_ACQUISITION_COST",
        "expected_brands": ["LUXE_LIVING"],
        "expected_sales_channels": ["WAYFAIR", "OVERSTOCK"],
        "current_period_start_date": "2024-03-15",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "Calculate the Return on Ad Spend for GourmetDelight on Google Shopping and Walmart Marketplace between January 1, 2024 and June 9, 2024.",
        "expected_metric": "RETURN_ON_AD_SPEND",
        "expected_brands": ["GOURMET_DELIGHT"],
        "expected_sales_channels": ["GOOGLE_SHOPPING", "WALMART_MARKETPLACE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Net Profit Margin for PetPal on Etsy and Shopify from April 1, 2024 to June 9, 2024?",
        "expected_metric": "NET_PROFIT_MARGIN",
        "expected_brands": ["PET_PAL"],
        "expected_sales_channels": ["ETSY", "SHOPIFY"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Determine the Repeat Purchase Rate for BeautyBliss on their Own Website and Physical Stores from February 15, 2024 to May 15, 2024.",
        "expected_metric": "REPEAT_PURCHASE_RATE",
        "expected_brands": ["BEAUTY_BLISS"],
        "expected_sales_channels": ["OWN_WEBSITE", "PHYSICAL_STORES"],
        "current_period_start_date": "2024-02-15",
        "current_period_end_date": "2024-05-15",
    },
    {
        "question": "What was the Average Time to Purchase for Toyota on their Own Website from January 1, 2024 to June 9, 2024?",
        "expected_metric": "AVG_TIME_TO_PURCHASE",
        "expected_brands": ["TOYOTA"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Calculate the Product Return Rate for Zara on Instagram Shopping and Facebook Marketplace between March 1, 2024 and May 31, 2024.",
        "expected_metric": "PRODUCT_RETURN_RATE",
        "expected_brands": ["ZARA"],
        "expected_sales_channels": ["INSTAGRAM_SHOPPING", "FACEBOOK_MARKETPLACE"],
        "current_period_start_date": "2024-03-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "What was the Customer Retention Rate for BookWorm on Amazon and their Own Website from April 1, 2024 to June 9, 2024?",
        "expected_metric": "CUSTOMER_RETENTION_RATE",
        "expected_brands": ["BOOK_WORM"],
        "expected_sales_channels": ["AMAZON", "OWN_WEBSITE"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Determine the Email Click-Through Rate for GreenThumb on their Own Website from February 1, 2024 to April 30, 2024.",
        "expected_metric": "EMAIL_CTR",
        "expected_brands": ["GREEN_THUMB"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-02-01",
        "current_period_end_date": "2024-04-30",
    },
    {
        "question": "What was the Site Traffic for ToyWorld on Google Shopping and Target Plus from May 1, 2024 to June 9, 2024?",
        "expected_metric": "SITE_TRAFFIC",
        "expected_brands": ["TOY_WORLD"],
        "expected_sales_channels": ["GOOGLE_SHOPPING", "TARGET_PLUS"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Calculate the Mobile Traffic Percentage for Adidas on their Own Website and Physical Stores between January 15, 2024 and April 15, 2024.",
        "expected_metric": "MOBILE_TRAFFIC_PERCENTAGE",
        "expected_brands": ["ADIDAS"],
        "expected_sales_channels": ["OWN_WEBSITE", "PHYSICAL_STORES"],
        "current_period_start_date": "2024-01-15",
        "current_period_end_date": "2024-04-15",
    },
    {
        "question": "What was the Average Session Duration for MusicMaster on Newegg and eBay from March 1, 2024 to May 31, 2024?",
        "expected_metric": "AVG_SESSION_DURATION",
        "expected_brands": ["MUSIC_MASTER"],
        "expected_sales_channels": ["NEWEGG", "EBAY"],
        "current_period_start_date": "2024-03-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "What was the Total Revenue for Apple on Amazon and their Own Website from January 1, 2024 to March 31, 2024?",
        "expected_metric": "TOTAL_REVENUE",
        "expected_brands": ["APPLE"],
        "expected_sales_channels": ["AMAZON", "OWN_WEBSITE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-03-31",
    },
    {
        "question": "Calculate the Average Order Value for Nike products on Instagram Shopping and Facebook Marketplace between April 15, 2024 and June 1, 2024.",
        "expected_metric": "AVG_ORDER_VALUE",
        "expected_brands": ["NIKE"],
        "expected_sales_channels": ["INSTAGRAM_SHOPPING", "FACEBOOK_MARKETPLACE"],
        "current_period_start_date": "2024-04-15",
        "current_period_end_date": "2024-06-01",
    },
    {
        "question": "What was the Conversion Rate for Samsung on their Own Website from May 1, 2024 to June 9, 2024?",
        "expected_metric": "CONVERSION_RATE",
        "expected_brands": ["SAMSUNG"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Determine the Customer Lifetime Value for FitFlex and EcoGreen on Amazon and eBay from February 1, 2024 to April 30, 2024.",
        "expected_metric": "CUSTOMER_LIFETIME_VALUE",
        "expected_brands": ["FIT_FLEX", "ECO_GREEN"],
        "expected_sales_channels": ["AMAZON", "EBAY"],
        "current_period_start_date": "2024-02-01",
        "current_period_end_date": "2024-04-30",
    },
    {
        "question": "What was the Customer Acquisition Cost for Luxe Living on Wayfair and Overstock from March 15, 2024 to May 31, 2024?",
        "expected_metric": "CUSTOMER_ACQUISITION_COST",
        "expected_brands": ["LUXE_LIVING"],
        "expected_sales_channels": ["WAYFAIR", "OVERSTOCK"],
        "current_period_start_date": "2024-03-15",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "Calculate the Return on Ad Spend for GourmetDelight on Google Shopping and Walmart Marketplace between January 1, 2024 and June 9, 2024.",
        "expected_metric": "RETURN_ON_AD_SPEND",
        "expected_brands": ["GOURMET_DELIGHT"],
        "expected_sales_channels": ["GOOGLE_SHOPPING", "WALMART_MARKETPLACE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Net Profit Margin for PetPal on Etsy and Shopify from April 1, 2024 to June 9, 2024?",
        "expected_metric": "NET_PROFIT_MARGIN",
        "expected_brands": ["PET_PAL"],
        "expected_sales_channels": ["ETSY", "SHOPIFY"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Determine the Repeat Purchase Rate for BeautyBliss on their Own Website and Physical Stores from February 15, 2024 to May 15, 2024.",
        "expected_metric": "REPEAT_PURCHASE_RATE",
        "expected_brands": ["BEAUTY_BLISS"],
        "expected_sales_channels": ["OWN_WEBSITE", "PHYSICAL_STORES"],
        "current_period_start_date": "2024-02-15",
        "current_period_end_date": "2024-05-15",
    },
    {
        "question": "What was the Average Time to Purchase for Toyota on their Own Website from January 1, 2024 to June 9, 2024?",
        "expected_metric": "AVG_TIME_TO_PURCHASE",
        "expected_brands": ["TOYOTA"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Calculate the Product Return Rate for Zara on Instagram Shopping and Facebook Marketplace between March 1, 2024 and May 31, 2024.",
        "expected_metric": "PRODUCT_RETURN_RATE",
        "expected_brands": ["ZARA"],
        "expected_sales_channels": ["INSTAGRAM_SHOPPING", "FACEBOOK_MARKETPLACE"],
        "current_period_start_date": "2024-03-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "What was the Customer Retention Rate for BookWorm on Amazon and their Own Website from April 1, 2024 to June 9, 2024?",
        "expected_metric": "CUSTOMER_RETENTION_RATE",
        "expected_brands": ["BOOK_WORM"],
        "expected_sales_channels": ["AMAZON", "OWN_WEBSITE"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Determine the Email Click-Through Rate for GreenThumb on their Own Website from February 1, 2024 to April 30, 2024.",
        "expected_metric": "EMAIL_CTR",
        "expected_brands": ["GREEN_THUMB"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-02-01",
        "current_period_end_date": "2024-04-30",
    },
    {
        "question": "What was the Site Traffic for ToyWorld on Google Shopping and Target Plus from May 1, 2024 to June 9, 2024?",
        "expected_metric": "SITE_TRAFFIC",
        "expected_brands": ["TOY_WORLD"],
        "expected_sales_channels": ["GOOGLE_SHOPPING", "TARGET_PLUS"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Calculate the Mobile Traffic Percentage for Adidas on their Own Website and Physical Stores between January 15, 2024 and April 15, 2024.",
        "expected_metric": "MOBILE_TRAFFIC_PERCENTAGE",
        "expected_brands": ["ADIDAS"],
        "expected_sales_channels": ["OWN_WEBSITE", "PHYSICAL_STORES"],
        "current_period_start_date": "2024-01-15",
        "current_period_end_date": "2024-04-15",
    },
    {
        "question": "What was the Average Session Duration for MusicMaster on Newegg and eBay from March 1, 2024 to May 31, 2024?",
        "expected_metric": "AVG_SESSION_DURATION",
        "expected_brands": ["MUSIC_MASTER"],
        "expected_sales_channels": ["NEWEGG", "EBAY"],
        "current_period_start_date": "2024-03-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "Calculate the Bounce Rate for CraftCorner on Etsy and their Own Website between February 1, 2024 and April 30, 2024.",
        "expected_metric": "BOUNCE_RATE",
        "expected_brands": ["CRAFT_CORNER"],
        "expected_sales_channels": ["ETSY", "OWN_WEBSITE"],
        "current_period_start_date": "2024-02-01",
        "current_period_end_date": "2024-04-30",
    },
    {
        "question": "What was the Pages per Session for Microsoft products on Amazon and Newegg from April 1, 2024 to June 9, 2024?",
        "expected_metric": "PAGES_PER_SESSION",
        "expected_brands": ["MICROSOFT"],
        "expected_sales_channels": ["AMAZON", "NEWEGG"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Determine the Add to Cart Rate for Coca-Cola on Walmart Marketplace and their Own Website from January 1, 2024 to March 31, 2024.",
        "expected_metric": "ADD_TO_CART_RATE",
        "expected_brands": ["COCA_COLA"],
        "expected_sales_channels": ["WALMART_MARKETPLACE", "OWN_WEBSITE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-03-31",
    },
    {
        "question": "What was the Checkout Completion Rate for AutoPro on eBay and Amazon from May 1, 2024 to June 9, 2024?",
        "expected_metric": "CHECKOUT_COMPLETION_RATE",
        "expected_brands": ["AUTO_PRO"],
        "expected_sales_channels": ["EBAY", "AMAZON"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Calculate the Average Order Size for HomeSmart on Google Shopping and Instagram Shopping between March 15, 2024 and May 31, 2024.",
        "expected_metric": "AVG_ORDER_SIZE",
        "expected_brands": ["HOME_SMART"],
        "expected_sales_channels": ["GOOGLE_SHOPPING", "INSTAGRAM_SHOPPING"],
        "current_period_start_date": "2024-03-15",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "What was the Revenue per Visitor for FreshFarms on their Own Website and Physical Stores from February 15, 2024 to May 15, 2024?",
        "expected_metric": "REVENUE_PER_VISITOR",
        "expected_brands": ["FRESH_FARMS"],
        "expected_sales_channels": ["OWN_WEBSITE", "PHYSICAL_STORES"],
        "current_period_start_date": "2024-02-15",
        "current_period_end_date": "2024-05-15",
    },
    {
        "question": "Determine the Customer Satisfaction Score for Google products on their Own Website from April 1, 2024 to June 9, 2024.",
        "expected_metric": "CUSTOMER_SATISFACTION_SCORE",
        "expected_brands": ["GOOGLE"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Net Promoter Score for Nestle on Amazon and Walmart Marketplace from January 1, 2024 to March 31, 2024?",
        "expected_metric": "NET_PROMOTER_SCORE",
        "expected_brands": ["NESTLE"],
        "expected_sales_channels": ["AMAZON", "WALMART_MARKETPLACE"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-03-31",
    },
    {
        "question": "Calculate the Average Response Time for TravelEase customer support on their Own Website between May 1, 2024 and June 9, 2024.",
        "expected_metric": "AVG_RESPONSE_TIME",
        "expected_brands": ["TRAVEL_EASE"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "What was the Social Media Engagement Rate for FitBit on Facebook Marketplace and Instagram Shopping from March 1, 2024 to May 31, 2024?",
        "expected_metric": "SOCIAL_MEDIA_ENGAGEMENT_RATE",
        "expected_brands": ["FITBIT"],
        "expected_sales_channels": ["FACEBOOK_MARKETPLACE", "INSTAGRAM_SHOPPING"],
        "current_period_start_date": "2024-03-01",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "Determine the Inventory Turnover Ratio for CozyHome on Wayfair and Overstock from February 1, 2024 to April 30, 2024.",
        "expected_metric": "INVENTORY_TURNOVER_RATIO",
        "expected_brands": ["COZY_HOME"],
        "expected_sales_channels": ["WAYFAIR", "OVERSTOCK"],
        "current_period_start_date": "2024-02-01",
        "current_period_end_date": "2024-04-30",
    },
    {
        "question": "What was the Out-of-Stock Rate for Disney merchandise on their Own Website and Physical Stores from April 15, 2024 to June 9, 2024?",
        "expected_metric": "OUT_OF_STOCK_RATE",
        "expected_brands": ["DISNEY"],
        "expected_sales_channels": ["OWN_WEBSITE", "PHYSICAL_STORES"],
        "current_period_start_date": "2024-04-15",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Calculate the Average Shipping Time for Sony products on Amazon and eBay between January 1, 2024 and March 31, 2024.",
        "expected_metric": "AVG_SHIPPING_TIME",
        "expected_brands": ["SONY"],
        "expected_sales_channels": ["AMAZON", "EBAY"],
        "current_period_start_date": "2024-01-01",
        "current_period_end_date": "2024-03-31",
    },
    {
        "question": "What was the On-Time Delivery Rate for OfficeMax on their Own Website from May 1, 2024 to June 9, 2024?",
        "expected_metric": "ON_TIME_DELIVERY_RATE",
        "expected_brands": ["OFFICE_MAX"],
        "expected_sales_channels": ["OWN_WEBSITE"],
        "current_period_start_date": "2024-05-01",
        "current_period_end_date": "2024-06-09",
    },
    {
        "question": "Determine the Average Discount per Order for SportsPro on Google Shopping and Walmart Marketplace from March 15, 2024 to May 31, 2024.",
        "expected_metric": "AVG_DISCOUNT_PER_ORDER",
        "expected_brands": ["SPORTS_PRO"],
        "expected_sales_channels": ["GOOGLE_SHOPPING", "WALMART_MARKETPLACE"],
        "current_period_start_date": "2024-03-15",
        "current_period_end_date": "2024-05-31",
    },
    {
        "question": "What was the Coupon Redemption Rate for BabyBliss on Etsy and their Own Website from February 15, 2024 to May 15, 2024?",
        "expected_metric": "COUPON_REDEMPTION_RATE",
        "expected_brands": ["BABY_BLISS"],
        "expected_sales_channels": ["ETSY", "OWN_WEBSITE"],
        "current_period_start_date": "2024-02-15",
        "current_period_end_date": "2024-05-15",
    },
    {
        "question": "Calculate the Gross Merchandise Value for McDonald's on their Own Website and Physical Stores between April 1, 2024 and June 9, 2024.",
        "expected_metric": "GROSS_MERCHANDISE_VALUE",
        "expected_brands": ["MCDONALDS"],
        "expected_sales_channels": ["OWN_WEBSITE", "PHYSICAL_STORES"],
        "current_period_start_date": "2024-04-01",
        "current_period_end_date": "2024-06-09",
    },
]
